<a href="https://colab.research.google.com/github/akashqchem/drug-potency-regression/blob/main/Copy_of_Drug_potency_find_out.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Importing all the necessary libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#Importing the dataset

In [2]:
dataset = pd.read_csv("Linear_regression_dataset.csv")
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
missing_data = dataset.isnull().sum()


##Printing Matrix of Features (x)

In [4]:
print (x)

[[24.]
 [60.]
 [74.]
 ...
 [ 0.]
 [99.]
 [67.]]


##Printing dependent variable vector (y)

In [5]:
print (y)

[6.09857 6.00393 6.79958 ... 5.78844 6.13687 6.04006]


##Printing if there are any missing values in the dataset

In [6]:
print (missing_data)

PCT_INHB_DD2    0
pXC50_3D7       0
dtype: int64


#Splitting the entire dataset into training & test sets

In [7]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split (x, y, test_size= 0.2, random_state =1)

## Printing all the separate datasets for the traning as well as test sets

In [8]:
print (x_train)
print (y_train)
print (x_test)
print (y_test)

[[100.]
 [  2.]
 [ 55.]
 ...
 [ 83.]
 [ 79.]
 [ 77.]]
[6.66439 6.00417 6.06631 ... 5.97426 6.05754 6.14984]
[[35.]
 [48.]
 [86.]
 ...
 [99.]
 [ 1.]
 [ 0.]]
[6.14515 5.90248 6.1877  ... 6.20271 5.97786 5.89416]


#Building & training our very first simple linear regression model

In [9]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

#Predicting with test set data

In [10]:
y_pred = regressor.predict(x_test)
print (y_pred)

[6.16847558 6.21843007 6.36445089 ... 6.41440538 6.03782537 6.03398272]


#Visualising our training set results

In [11]:
plt.scatter (x_train, y_train, color = "red")
plt.plot (x_train, regressor.predict(x_train), color = 'blue')
plt.title ("Percentage Inhibition vs Drug Potency (Training Set)")
plt.xlabel ("Percentage Inhibition (%)")
plt.ylabel ("Drug Potency (pIC50)")
plt.show()

#Visualising our test set results

In [12]:
plt.scatter (x_test, y_test, color = "red")
plt.plot (x_train, regressor.predict(x_train), color = 'blue')
plt.title ("Percentage Inhibition vs Drug Potency (Test Set)") #convention is always x vs y
plt.xlabel ("Percentage Inhibition (%)")
plt.ylabel ("Drug Potency (pIC50)")
plt.show()

# Simple linear regression model to make a single prediction

In [14]:
print (regressor.predict([[85]]))
print (regressor.predict([[95]]))


[6.36060823]
[6.39903476]


## Getting the final linear regression equation with the values of the coefficients

In [15]:
print(regressor.coef_)
print(regressor.intercept_)

[0.00384265]
6.033982719639366


#