<a href="https://colab.research.google.com/github/akashqchem/Machine_Learning_Regression_Models/blob/main/Polynomial_Regression_Fish_Weight_Analysis/Polynomial_Linear_Regression_Fish_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Importing all the necessary libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


#Importing the dataset "Fish.csv"

In [ ]:
dataset = pd.read_csv ("Fish.csv")
x = dataset.iloc[:, 1:-1].values  #This will print all the matrix of features
y = dataset.iloc[:, -1].values    #This will print all the dependent variable vectors
missing_data = dataset.isnull().sum()

##Printing matrix of features (x), dependent variable (y), & missing_data if available

In [ ]:
print (x)
print (y)
print (missing_data)

[[ 242.     23.2    25.4    30.     11.52]
 [ 290.     24.     26.3    31.2    12.48]
 [ 340.     23.9    26.5    31.1    12.38]
 [ 363.     26.3    29.     33.5    12.73]
 [ 430.     26.5    29.     34.     12.44]
 [ 450.     26.8    29.7    34.7    13.6 ]
 [ 500.     26.8    29.7    34.5    14.18]
 [ 390.     27.6    30.     35.     12.67]
 [ 450.     27.6    30.     35.1    14.  ]
 [ 500.     28.5    30.7    36.2    14.23]
 [ 475.     28.4    31.     36.2    14.26]
 [ 500.     28.7    31.     36.2    14.37]
 [ 500.     29.1    31.5    36.4    13.76]
 [ 340.     29.5    32.     37.3    13.91]
 [ 600.     29.4    32.     37.2    14.95]
 [ 600.     29.4    32.     37.2    15.44]
 [ 700.     30.4    33.     38.3    14.86]
 [ 700.     30.4    33.     38.5    14.94]
 [ 610.     30.9    33.5    38.6    15.63]
 [ 650.     31.     33.5    38.7    14.47]
 [ 575.     31.3    34.     39.5    15.13]
 [ 685.     31.4    34.     39.2    15.99]
 [ 620.     31.5    34.5    39.7    15.52]
 [ 680.    

#Splitting the entire dataset into training & test sets

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split (x, y, test_size = 0.2, random_state = 1) #Splitting the entire dataset

##Printing all x_train, y_train, x_test, & y_test

In [ ]:
print (x_train)
print (y_train)
print (x_test)
print (y_test)

[[ 840.     32.5    35.     37.3    11.49]
 [ 300.     34.8    37.3    39.8     6.29]
 [ 540.     28.5    31.     34.     10.74]
 [ 300.     25.2    27.3    28.7     8.32]
 [ 160.     21.1    22.5    25.      6.4 ]
 [ 200.     21.2    23.     25.8    10.35]
 [ 975.     37.4    41.     45.9    18.64]
 [ 270.     24.1    26.5    29.3     8.15]
 [ 430.     35.5    38.     40.5     7.29]
 [ 556.     32.     34.5    36.5    10.26]
 [ 250.     25.9    28.     29.4     7.82]
 [  12.2    11.5    12.2    13.4     2.09]
 [ 500.     29.1    31.5    36.4    13.76]
 [ 700.     34.5    37.     39.4    10.84]
 [  51.5    15.     16.2    17.2     4.59]
 [ 850.     32.8    36.     41.6    16.89]
 [ 272.     25.     27.     30.6     8.57]
 [ 650.     36.5    39.     41.4    11.14]
 [ 540.     40.1    43.     45.8     7.79]
 [ 700.     30.4    33.     38.5    14.94]
 [ 100.     16.2    18.     19.2     5.22]
 [  19.7    13.2    14.3    15.2     2.87]
 [ 340.     29.5    32.     37.3    13.91]
 [  78.    

#Building & training our Polynomial Linear Regression model

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
Poly_reg = PolynomialFeatures(degree = 4) #create the PolynomialFeatures object named as Poly_reg
x_poly = Poly_reg.fit_transform(x_train) #Transform x_train into PolynomialFeatures (x_poly)
Lin_reg = LinearRegression() #Create the LinearRegression model
Lin_reg.fit (x_poly, y_train) #Train that LinearRegression model using PolynomialFeatures & y_train

LinearRegression()

#Predicting the test set results

In [ ]:
y_pred = Lin_reg.predict(Poly_reg.fit_transform (x_test)) #This will print all the predicted values of the x_test

##Displaying the results of two vectors, one for the predicted values of the x_test & one for the actual values of the same x_test

In [ ]:
np.set_printoptions(precision = 2)
print(np.concatenate ((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[6.52 6.6 ]
 [3.49 3.29]
 [5.37 5.17]
 [3.53 3.62]
 [3.09 2.77]
 [5.36 5.73]
 [3.62 3.55]
 [4.53 4.81]
 [1.26 3.35]
 [3.56 3.83]
 [3.49 3.52]
 [3.42 3.63]
 [2.36 2.  ]
 [4.31 4.57]
 [8.27 6.57]
 [3.52 4.  ]
 [2.95 3.29]
 [5.92 5.36]
 [4.98 4.77]
 [3.86 4.24]
 [1.19 1.15]
 [2.66 2.27]
 [3.75 3.91]
 [5.16 4.93]
 [3.4  3.67]
 [6.28 6.29]
 [5.35 5.29]
 [1.26 1.05]
 [9.66 6.14]
 [3.54 3.63]
 [8.08 7.6 ]
 [4.36 4.33]]


#Making a single prediction by our trained Polynomial Linear Regression Model

In [ ]:
print (Lin_reg.predict(Poly_reg.fit_transform([[242, 23, 25, 30, 11]]))) #Note:Predict method always expects a 2D array
print (Lin_reg.predict(Poly_reg.fit_transform([[290, 24, 26.3, 31.2, 12.48]])))

[4.05]
[4.49]


#Printing all the values of the final slope coefficients & intercept

In [ ]:
print (Lin_reg.coef_)   #Prints the coefficients for each polynomial feature
print (Lin_reg.intercept_) #Prints the intercept of the polynomial regression model

[ 1.21e-03  3.04e-01  3.50e-02  2.24e-02  4.31e-02  4.26e-03  7.48e-04
  2.66e-02 -1.02e-01  4.87e-02 -3.31e-02  3.87e-02 -1.86e-02  4.92e-02
 -1.05e-02 -1.06e-01 -4.50e-02 -1.51e-02  4.35e-02 -4.51e-03  2.63e-02
  5.36e-07 -2.74e-04  1.47e-04  7.65e-05 -9.31e-05  6.60e-02 -3.39e-02
 -8.90e-02  3.89e-02 -2.80e-02  8.97e-02 -3.03e-02 -3.90e-03 -4.12e-03
  2.98e-03 -1.57e-01  3.38e-02  2.96e-02 -4.51e-02  1.14e-01  3.97e-02
  2.97e-02  1.21e-01 -5.20e-02 -3.32e-02  5.45e-02 -1.27e-01  8.84e-02
 -1.47e-01 -1.19e-03  3.35e-02  3.89e-02 -1.26e-02 -4.06e-04 -1.46e-02
 -1.86e-10 -2.08e-07  3.13e-07 -1.05e-07 -8.41e-09  2.24e-04 -2.95e-04
 -1.20e-04  7.97e-05  5.90e-05  1.49e-04 -7.43e-05 -1.53e-05 -1.03e-06
  5.58e-06 -2.20e-02  3.25e-02  2.60e-02 -2.19e-02 -6.43e-03 -4.52e-02
  3.13e-02 -6.04e-05  8.07e-03 -3.87e-03 -2.26e-03  1.43e-02 -1.00e-02
  4.08e-03 -7.11e-03  2.54e-03 -9.89e-04 -4.77e-04  1.08e-03 -3.55e-04
  2.94e-02 -4.34e-02  4.23e-02  1.44e-01 -7.24e-02  1.41e-01 -3.53e-02
 -2.28