#Importing all the necessary libraries

In [38]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#Importing our dataset 'QM9_HOMO_LUMO_Gap.csv'

In [39]:
dataset = pd.read_csv ("QM9_HOMO_LUMO_Gap.csv")
x = dataset.iloc [:, :-1].values  #This will print all the matrix of features
y = dataset.iloc [:, -1].values   #This will print all the dependent variable vectors
missing_data = dataset.isnull().sum() #This will print if there are missing_data in the dataset

##Printing matrix of features (x), dependent variable (y), & missing_data if available

In [40]:
print (x)
print (y)
print (missing_data)

[[ 1.58e+02  1.58e+02  1.58e+02 ... -3.99e+02 -4.01e+02 -3.72e+02]
 [ 2.94e+02  2.94e+02  1.91e+02 ... -2.79e+02 -2.80e+02 -2.59e+02]
 [ 8.00e+02  4.38e+02  2.83e+02 ... -2.14e+02 -2.15e+02 -2.01e+02]
 ...
 [ 3.39e+00  2.36e+00  1.40e+00 ... -1.40e+03 -1.41e+03 -1.30e+03]
 [ 3.31e+00  2.38e+00  1.40e+00 ... -1.47e+03 -1.47e+03 -1.36e+03]
 [ 3.30e+00  2.42e+00  1.41e+00 ... -1.44e+03 -1.45e+03 -1.34e+03]]
[0.5  0.34 0.36 ... 0.19 0.17 0.17]
A            0
B            0
C            0
mu           0
alpha        0
homo         0
lumo         0
r2           0
zpve         0
u0           0
u298         0
h298         0
g298         0
cv           0
u0_atom      0
u298_atom    0
h298_atom    0
g298_atom    0
gap          0
dtype: int64


#Splitting the entire dataset into training & test sets

In [41]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split (x, y, test_size = 0.2, random_state = 1 ) #Splitting the entire dataset

#Building our multiple linear regression model & also trained our model

In [42]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression ()    #Built our model
regressor.fit (x_train, y_train)    #Trained our model using fit method


LinearRegression()

#Predicting the test set results by displaying results of two vectors

In [43]:
y_pred = (regressor.predict (x_test)) #Predicted values of the x_test
np.set_printoptions (precision = 2)   #This will display our results with 2 decimal places
print (np.concatenate ((y_pred.reshape (len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1)) #This will display the results of two vectors side by side

[[0.22 0.22]
 [0.24 0.24]
 [0.21 0.21]
 ...
 [0.17 0.17]
 [0.29 0.29]
 [0.34 0.34]]


#Evaluating the Model Performance (R² Score)

In [44]:
from sklearn.metrics import r2_score
print(r2_score(y_test, y_pred))

0.9999990061707499
