<a href="https://colab.research.google.com/github/akashqchem/Machine_Learning_Regression_Models/blob/main/QM9_Model_Comparison_Regression/Polynomial_Linear_Regression_QM9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Importing all the necessary libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


#Importing the dataset "QM9_HOMO_LUMO_Gap.csv"

In [ ]:
dataset = pd.read_csv ("QM9_HOMO_LUMO_Gap.csv")
x = dataset.iloc[:, 1:-1].values  #This will print all the matrix of features
y = dataset.iloc[:, -1].values    #This will print all the dependent variable vectors
missing_data = dataset.isnull().sum()

##Printing matrix of features (x), dependent variable (y), & missing_data if available

In [ ]:
print (x)
print (y)
print (missing_data)

[[ 1.58e+02  1.58e+02  0.00e+00 ... -3.99e+02 -4.01e+02 -3.72e+02]
 [ 2.94e+02  1.91e+02  1.63e+00 ... -2.79e+02 -2.80e+02 -2.59e+02]
 [ 4.38e+02  2.83e+02  1.85e+00 ... -2.14e+02 -2.15e+02 -2.01e+02]
 ...
 [ 2.36e+00  1.40e+00  2.14e+00 ... -1.40e+03 -1.41e+03 -1.30e+03]
 [ 2.38e+00  1.40e+00  3.25e+00 ... -1.47e+03 -1.47e+03 -1.36e+03]
 [ 2.42e+00  1.41e+00  1.99e+00 ... -1.44e+03 -1.45e+03 -1.34e+03]]
[0.5  0.34 0.36 ... 0.19 0.17 0.17]
A            0
B            0
C            0
mu           0
alpha        0
homo         0
lumo         0
r2           0
zpve         0
u0           0
u298         0
h298         0
g298         0
cv           0
u0_atom      0
u298_atom    0
h298_atom    0
g298_atom    0
gap          0
dtype: int64


#Splitting the entire dataset into training & test sets

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split (x, y, test_size = 0.2, random_state = 1) #Splitting the entire dataset

#Building & training our Polynomial Linear Regression model

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
Poly_reg = PolynomialFeatures(degree = 4) #create the PolynomialFeatures object named as Poly_reg
x_poly = Poly_reg.fit_transform(x_train) #Transform x_train into PolynomialFeatures (x_poly)
Lin_reg = LinearRegression() #Create the LinearRegression model
Lin_reg.fit (x_poly, y_train) #Train that LinearRegression model using PolynomialFeatures & y_train

LinearRegression()

#Predicting the test set results

In [ ]:
y_pred = Lin_reg.predict(Poly_reg.fit_transform (x_test)) #This will print all the predicted values of the x_test

##Displaying the results of two vectors, one for the predicted values of the x_test & one for the actual values of the same x_test

In [ ]:
np.set_printoptions(precision = 2)
print(np.concatenate ((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[0.22 0.22]
 [0.24 0.24]
 [0.21 0.21]
 ...
 [0.17 0.17]
 [0.29 0.29]
 [0.34 0.34]]


#Evaluating the Model Performance (R² Score)

In [ ]:
from sklearn.metrics import r2_score
print(r2_score(y_test, y_pred))

0.9049225479087277
