<a href="https://colab.research.google.com/github/akashqchem/breast_cancer_mean_radius_prediction_SVR/blob/main/Breast_Cancer_Mean_Radius_Prediction_SVR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Importing all the necessary libraries

In [268]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#Importing our dataset 'Breast_cancer_data.csv'

In [269]:
dataset = pd.read_csv("Breast_cancer_data.csv")
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
missing_data = dataset.isnull().sum()

##Printing all the matrix of features(x)

In [270]:
print(x)

[[8.42e+05 1.04e+01 1.23e+02 ... 2.65e-01 4.60e-01 1.19e-01]
 [8.43e+05 1.78e+01 1.33e+02 ... 1.86e-01 2.75e-01 8.90e-02]
 [8.43e+07 2.12e+01 1.30e+02 ... 2.43e-01 3.61e-01 8.76e-02]
 ...
 [9.27e+05 2.81e+01 1.08e+02 ... 1.42e-01 2.22e-01 7.82e-02]
 [9.27e+05 2.93e+01 1.40e+02 ... 2.65e-01 4.09e-01 1.24e-01]
 [9.28e+04 2.45e+01 4.79e+01 ... 0.00e+00 2.87e-01 7.04e-02]]


##Printing all the dependent variable vectors(y)

In [271]:
print (y)

[17.99 20.57 19.69 11.42 20.29 12.45 18.25 13.71 13.   12.46 16.02 15.78
 19.17 15.85 13.73 14.54 14.68 16.13 19.81 13.54 13.08  9.5  15.34 21.16
 16.65 17.14 14.58 18.61 15.3  17.57 18.63 11.84 17.02 19.27 16.13 16.74
 14.25 13.03 14.99 13.48 13.44 10.95 19.07 13.28 13.17 18.65  8.2  13.17
 12.05 13.49 11.76 13.64 11.94 18.22 15.1  11.52 19.21 14.71 13.05  8.62
 10.17  8.6  14.25  9.17 12.68 14.78  9.46 11.31  9.03 12.78 18.94  8.89
 17.2  13.8  12.31 16.07 13.53 18.05 20.18 12.86 11.45 13.34 25.22 19.1
 12.   18.46 14.48 19.02 12.36 14.64 14.62 15.37 13.27 13.45 15.06 20.26
 12.18  9.79 11.6  14.42 13.61  6.98 12.18  9.88 10.49 13.11 11.64 12.36
 22.27 11.34  9.78 12.63 14.26 10.51  8.73 11.93  8.95 14.87 15.78 17.95
 11.41 18.66 24.25 14.5  13.37 13.85 13.61 19.   15.1  19.79 12.19 15.46
 16.16 15.71 18.45 12.77 11.71 11.43 14.95 11.28  9.74 16.11 11.43 12.9
 10.75 11.9  11.8  14.95 14.44 13.74 13.    8.22  9.73 11.15 13.15 12.25
 17.68 16.84 12.06 10.9  11.75 19.19 19.59 12.34 23.2

##Printing if there are missing_data in the dataset

In [272]:
print(missing_data)

id                         0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
radius_mean                0
dtype: int64


#Converting y into 2D array (because StandardScaler class expects inputs as 2D array)

In [273]:
y = y.reshape(len(y), 1)

In [274]:
print (y)

[[17.99]
 [20.57]
 [19.69]
 [11.42]
 [20.29]
 [12.45]
 [18.25]
 [13.71]
 [13.  ]
 [12.46]
 [16.02]
 [15.78]
 [19.17]
 [15.85]
 [13.73]
 [14.54]
 [14.68]
 [16.13]
 [19.81]
 [13.54]
 [13.08]
 [ 9.5 ]
 [15.34]
 [21.16]
 [16.65]
 [17.14]
 [14.58]
 [18.61]
 [15.3 ]
 [17.57]
 [18.63]
 [11.84]
 [17.02]
 [19.27]
 [16.13]
 [16.74]
 [14.25]
 [13.03]
 [14.99]
 [13.48]
 [13.44]
 [10.95]
 [19.07]
 [13.28]
 [13.17]
 [18.65]
 [ 8.2 ]
 [13.17]
 [12.05]
 [13.49]
 [11.76]
 [13.64]
 [11.94]
 [18.22]
 [15.1 ]
 [11.52]
 [19.21]
 [14.71]
 [13.05]
 [ 8.62]
 [10.17]
 [ 8.6 ]
 [14.25]
 [ 9.17]
 [12.68]
 [14.78]
 [ 9.46]
 [11.31]
 [ 9.03]
 [12.78]
 [18.94]
 [ 8.89]
 [17.2 ]
 [13.8 ]
 [12.31]
 [16.07]
 [13.53]
 [18.05]
 [20.18]
 [12.86]
 [11.45]
 [13.34]
 [25.22]
 [19.1 ]
 [12.  ]
 [18.46]
 [14.48]
 [19.02]
 [12.36]
 [14.64]
 [14.62]
 [15.37]
 [13.27]
 [13.45]
 [15.06]
 [20.26]
 [12.18]
 [ 9.79]
 [11.6 ]
 [14.42]
 [13.61]
 [ 6.98]
 [12.18]
 [ 9.88]
 [10.49]
 [13.11]
 [11.64]
 [12.36]
 [22.27]
 [11.34]
 [ 9.78]
 

#Splitting the entire dataset into training & test sets

In [275]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

##Printing all the x_train, y_train, x_test, & y_test

In [276]:
print (x_train)
print (y_train)
print (x_test)
print (y_test)

[[9.05e+07 2.07e+01 1.18e+02 ... 1.97e-01 3.06e-01 8.50e-02]
 [8.44e+07 1.43e+01 1.35e+02 ... 1.63e-01 2.36e-01 7.68e-02]
 [8.93e+04 1.44e+01 5.64e+01 ... 1.39e-02 2.99e-01 7.80e-02]
 ...
 [8.60e+05 2.45e+01 1.14e+02 ... 1.90e-01 3.31e-01 1.34e-01]
 [8.82e+07 2.12e+01 8.98e+01 ... 7.96e-02 2.23e-01 7.62e-02]
 [8.55e+05 1.84e+01 8.26e+01 ... 5.01e-02 1.99e-01 6.17e-02]]
[[17.99]
 [20.29]
 [ 9.  ]
 [12.21]
 [12.34]
 [14.86]
 [13.54]
 [19.89]
 [20.55]
 [11.99]
 [12.88]
 [23.21]
 [14.87]
 [16.84]
 [19.59]
 [20.18]
 [12.27]
 [15.73]
 [12.3 ]
 [19.07]
 [11.08]
 [15.75]
 [17.54]
 [15.71]
 [11.22]
 [14.99]
 [15.05]
 [19.4 ]
 [11.89]
 [15.22]
 [14.96]
 [14.68]
 [10.32]
 [11.85]
 [11.66]
 [15.49]
 [12.18]
 [11.13]
 [14.34]
 [11.8 ]
 [14.8 ]
 [13.2 ]
 [15.1 ]
 [12.89]
 [13.7 ]
 [ 9.78]
 [14.02]
 [12.89]
 [11.36]
 [16.26]
 [11.43]
 [12.85]
 [18.25]
 [19.44]
 [15.78]
 [12.87]
 [11.16]
 [11.52]
 [13.05]
 [14.2 ]
 [12.07]
 [11.61]
 [ 9.72]
 [12.34]
 [14.92]
 [ 6.98]
 [11.54]
 [10.49]
 [13.71]
 [ 9.04

#Applying feature scaling (Standardisation) to all these splitted datasets

In [277]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
sc_y = StandardScaler()
x_train[:, 0:30] = sc_x.fit_transform(x_train[:, 0:30])
x_test[:, 0:30] = sc_x.transform(x_test[:, 0:30])
y_train = sc_y.fit_transform(y_train)
y_test = sc_y.transform(y_test)

In [278]:
print(x_train)

[[ 0.4   0.3   1.01 ...  1.22  0.3   0.08]
 [ 0.36 -1.14  1.7  ...  0.7  -0.89 -0.41]
 [-0.25 -1.13 -1.45 ... -1.52  0.18 -0.34]
 ...
 [-0.25  1.18  0.87 ...  1.11  0.73  3.02]
 [ 0.38  0.43 -0.11 ... -0.54 -1.12 -0.45]
 [-0.25 -0.21 -0.4  ... -0.98 -1.53 -1.32]]


In [279]:
print (x_test)

[[-0.25 -1.22  0.23 ... -0.07 -0.1   0.51]
 [-0.25 -0.16 -0.26 ...  1.39  1.73  2.06]
 [-0.25 -0.76 -0.38 ... -0.15  0.84  0.73]
 ...
 [-0.25 -0.46 -1.35 ...  0.88  2.29  2.04]
 [-0.25 -0.    0.07 ... -0.3  -0.7  -0.54]
 [ 0.4  -0.81 -0.17 ... -1.24 -1.75 -0.93]]


In [280]:
print(y_train)

[[ 1.04e+00]
 [ 1.68e+00]
 [-1.44e+00]
 [-5.54e-01]
 [-5.18e-01]
 [ 1.79e-01]
 [-1.86e-01]
 [ 1.57e+00]
 [ 1.75e+00]
 [-6.15e-01]
 [-3.69e-01]
 [ 2.49e+00]
 [ 1.82e-01]
 [ 7.27e-01]
 [ 1.49e+00]
 [ 1.65e+00]
 [-5.38e-01]
 [ 4.20e-01]
 [-5.29e-01]
 [ 1.34e+00]
 [-8.67e-01]
 [ 4.25e-01]
 [ 9.20e-01]
 [ 4.14e-01]
 [-8.28e-01]
 [ 2.15e-01]
 [ 2.31e-01]
 [ 1.44e+00]
 [-6.43e-01]
 [ 2.79e-01]
 [ 2.07e-01]
 [ 1.29e-01]
 [-1.08e+00]
 [-6.54e-01]
 [-7.07e-01]
 [ 3.53e-01]
 [-5.63e-01]
 [-8.53e-01]
 [ 3.50e-02]
 [-6.68e-01]
 [ 1.62e-01]
 [-2.80e-01]
 [ 2.45e-01]
 [-3.66e-01]
 [-1.42e-01]
 [-1.23e+00]
 [-5.35e-02]
 [-3.66e-01]
 [-7.90e-01]
 [ 5.66e-01]
 [-7.70e-01]
 [-3.77e-01]
 [ 1.12e+00]
 [ 1.45e+00]
 [ 4.33e-01]
 [-3.72e-01]
 [-8.45e-01]
 [-7.45e-01]
 [-3.22e-01]
 [-3.73e-03]
 [-5.93e-01]
 [-7.20e-01]
 [-1.24e+00]
 [-5.18e-01]
 [ 1.95e-01]
 [-2.00e+00]
 [-7.40e-01]
 [-1.03e+00]
 [-1.39e-01]
 [-1.43e+00]
 [ 5.41e-01]
 [ 1.55e+00]
 [ 9.01e-01]
 [-2.53e-01]
 [ 1.23e+00]
 [-4.77e-01]
 [-3.47e-01]

In [281]:
print(y_test)

[[ 0.13]
 [-0.29]
 [-0.35]
 [ 1.13]
 [ 0.25]
 [ 0.54]
 [ 1.38]
 [ 1.07]
 [-1.03]
 [ 0.09]
 [-0.88]
 [-0.01]
 [ 0.56]
 [-0.51]
 [ 0.15]
 [-0.37]
 [-0.56]
 [-0.7 ]
 [-1.01]
 [ 1.73]
 [-0.4 ]
 [-0.73]
 [ 1.49]
 [-0.4 ]
 [ 0.16]
 [-0.81]
 [ 0.1 ]
 [ 1.18]
 [ 3.6 ]
 [ 0.77]
 [ 2.03]
 [-0.87]
 [ 0.53]
 [-0.06]
 [-1.31]
 [-0.03]
 [ 1.03]
 [ 0.11]
 [-0.9 ]
 [-0.69]
 [-1.36]
 [-0.2 ]
 [-0.68]
 [-0.23]
 [-0.18]
 [ 0.31]
 [-1.8 ]
 [-1.24]
 [ 0.12]
 [ 0.93]
 [ 1.05]
 [ 1.04]
 [-0.44]
 [-0.45]
 [-1.24]
 [-0.09]
 [-0.36]
 [ 1.27]
 [-0.15]
 [-1.09]
 [-0.92]
 [-0.49]
 [ 0.2 ]
 [-0.26]
 [-0.28]
 [-0.63]
 [-0.57]
 [ 1.74]
 [-0.53]
 [-0.67]
 [-0.39]
 [-0.4 ]
 [-0.21]
 [ 1.65]
 [-1.48]
 [ 0.4 ]
 [ 0.21]
 [-0.4 ]
 [-0.76]
 [ 0.53]
 [-0.8 ]
 [ 0.79]
 [-0.2 ]
 [ 0.59]
 [-0.35]
 [-0.78]
 [-0.11]
 [-0.16]
 [ 0.01]
 [-0.69]
 [-0.28]
 [-0.66]
 [-1.09]
 [-1.01]
 [ 1.02]
 [-0.49]
 [-1.55]
 [-0.43]
 [-0.79]
 [-0.6 ]
 [-0.7 ]
 [-0.72]
 [-1.16]
 [ 0.15]
 [ 0.05]
 [ 0.21]
 [-0.93]
 [-0.12]
 [ 1.03]
 [ 0.34]
 [-0.77]
 

#Building and training the SVR model on the training set (x_train, y_train) using the RBF kernel

In [282]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(x_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

#Predicting results for the test set (x_test) and applying inverse transformation to return to the original scale

In [283]:
y_pred = sc_y.inverse_transform(regressor.predict(x_test).reshape(-1, 1))

In [284]:
print(y_pred)

[[14.14]
 [12.92]
 [12.57]
 [18.01]
 [14.89]
 [16.42]
 [18.22]
 [17.36]
 [10.44]
 [14.58]
 [11.1 ]
 [13.82]
 [16.46]
 [12.34]
 [14.73]
 [13.2 ]
 [11.95]
 [11.51]
 [11.95]
 [19.83]
 [12.42]
 [11.35]
 [18.76]
 [12.45]
 [14.86]
 [11.25]
 [14.38]
 [18.59]
 [23.22]
 [17.02]
 [20.4 ]
 [10.81]
 [15.8 ]
 [14.04]
 [ 9.24]
 [14.01]
 [17.68]
 [14.5 ]
 [11.77]
 [11.76]
 [10.36]
 [13.72]
 [11.42]
 [13.39]
 [13.64]
 [14.72]
 [ 9.81]
 [10.06]
 [14.84]
 [17.68]
 [17.97]
 [18.36]
 [12.22]
 [12.02]
 [ 9.76]
 [14.08]
 [12.99]
 [18.27]
 [13.63]
 [10.1 ]
 [11.39]
 [14.27]
 [14.34]
 [14.3 ]
 [12.91]
 [12.03]
 [11.96]
 [20.33]
 [12.53]
 [11.54]
 [12.7 ]
 [12.64]
 [13.87]
 [19.87]
 [ 9.41]
 [17.4 ]
 [14.53]
 [12.52]
 [11.22]
 [15.95]
 [11.43]
 [17.34]
 [13.86]
 [16.31]
 [12.87]
 [11.52]
 [13.21]
 [13.47]
 [14.49]
 [11.42]
 [12.92]
 [12.58]
 [10.94]
 [11.49]
 [17.12]
 [12.07]
 [ 9.15]
 [12.55]
 [11.09]
 [11.74]
 [11.43]
 [11.48]
 [ 9.92]
 [14.91]
 [14.05]
 [14.83]
 [10.42]
 [13.44]
 [16.18]
 [15.41]
 [14.76]
 

#Displaying the predicted and actual results side by side

In [285]:
np.set_printoptions(precision = 2)
y_test = sc_y.inverse_transform(y_test)
print (np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[14.14 14.69]
 [12.92 13.17]
 [12.57 12.95]
 [18.01 18.31]
 [14.89 15.13]
 [16.42 16.16]
 [18.22 19.19]
 [17.36 18.08]
 [10.44 10.48]
 [14.58 14.53]
 [11.1  11.04]
 [13.82 14.19]
 [16.46 16.24]
 [12.34 12.36]
 [14.73 14.74]
 [13.2  12.88]
 [11.95 12.2 ]
 [11.51 11.68]
 [11.95 10.57]
 [19.83 20.48]
 [12.42 12.76]
 [11.35 11.57]
 [18.76 19.59]
 [12.45 12.75]
 [14.86 14.78]
 [11.25 11.3 ]
 [14.38 14.59]
 [18.59 18.46]
 [23.22 27.22]
 [17.02 17.01]
 [20.4  21.56]
 [10.81 11.06]
 [15.8  16.13]
 [14.04 13.98]
 [ 9.24  9.46]
 [14.01 14.11]
 [17.68 17.93]
 [14.5  14.62]
 [11.77 10.95]
 [11.76 11.71]
 [10.36  9.29]
 [13.72 13.49]
 [11.42 11.75]
 [13.39 13.37]
 [13.64 13.56]
 [14.72 15.32]
 [ 9.81  7.69]
 [10.06  9.74]
 [14.84 14.64]
 [17.68 17.57]
 [17.97 18.01]
 [18.36 17.99]
 [12.22 12.63]
 [12.02 12.58]
 [ 9.76  9.74]
 [14.08 13.9 ]
 [12.99 12.91]
 [18.27 18.81]
 [13.63 13.66]
 [10.1  10.26]
 [11.39 10.9 ]
 [14.27 12.46]
 [14.34 14.95]
 [14.3  13.27]
 [12.91 13.2 ]
 [12.03 11.94]
 [11.96 12

#Making a single prediction

In [286]:
y_new = (sc_y.inverse_transform(regressor.predict(sc_x.transform([[862547, 11.38, 125, 587, 0.2564, 0.6548, 0.5874, 0.1475, 0.2418, 0.07879, 0.6879, 1.153, 3.254, 68.23, 0.006400, 0.02568, 0.06255, 0.02785, 0.01867, 0.006134, 26.58, 24.12, 140.2, 800.5, 0.2097, 0.4246, 0.2547, 0.4875, 0.4526, 0.08759]])). reshape(-1,1)))

In [287]:
print ("Radius mean:", y_new)

Radius mean: [[15.17]]


#Congratulations! You’ve Successfully Built the Support Vector Regression (SVR) Model